package com.volmyr.warehouse_api_ms_v2.app;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) {
        throw new UnsupportedOperationException();
    }
}
